version: "3"

services:
  mysql:
    build:
        context: .
        dockerfile: Dockerfile
    platform: linux/x86_64
    container_name: testing-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
